name: Push-to-EC2
on:
  push:
    branches:
      - principal
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the files
      uses: actions/checkout@v3

    - name: Copy Frontend with SSH
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "./frontend/" 
        REMOTE_HOST: "ec2-18-117-111-112.us-east-2.compute.amazonaws.com"
        REMOTE_USER: "ec2-user"
        TARGET: "/app/gerenciadorCcr/frontend"  
        EXCLUDE: "/node_modules/, **.env"  

    - name: Copy Backend with SSH
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "./backend/" 
        REMOTE_HOST: "ec2-18-117-111-112.us-east-2.compute.amazonaws.com"
        REMOTE_USER: "ec2-user"
        TARGET: "/app/gerenciadorCcr/backend"  
        EXCLUDE: "/node_modules/, **.env"  
